[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3

; Configuration pour la Clean Architecture (Inclusion récursive)
build_flags = 
    -I src
    -I src/domain
    -I src/application
    -I src/infrastructure
    -D CORE_DEBUG_LEVEL=0
